FROM golang:1.15 as builder

WORKDIR /go/src/github.com/Alma-media/eop09/

ADD go.mod go.sum ./
RUN go mod download

ADD . /go/src/github.com/Alma-media/eop09
RUN CGO_ENABLED=0 GOOS=linux go build -o ./bin/server /go/src/github.com/Alma-media/eop09/server/main.go

FROM alpine:3.11.5

WORKDIR /app

COPY --from=builder /go/src/github.com/Alma-media/eop09/bin/server /app/

ENTRYPOINT ["/app/server"]